# E-Commerce Revenue Recovery & Conversion Optimization

**Author:** Mylene Gadeau
**Tools:** Google BigQuery, SQL, VS Code, GitHub, Markdown
**Dataset:** Google BigQuery GA4 Sample E-commerce Dataset
**SQL Dialect:** Google BigQuery Standard SQL
**Project Period:** November 1, 2020 to January 31, 2021

---

# 1. Project Overview

## 1.1 Project Title

**E-Commerce Revenue Recovery & Conversion Optimization**

## 1.2 Business Objective

The objective of this project is to analyze e-commerce customer behavior and identify where potential revenue is lost throughout the online shopping journey.

The analysis focuses on:

* Customer activity
* Product engagement
* Shopping funnel conversion
* Add-to-cart and checkout abandonment
* Purchase behavior
* Product performance
* Customer value and retention
* Traffic-source performance
* Potential revenue-recovery opportunities

The goal is to transform raw GA4 event data into a structured analytical dataset and use SQL to answer practical business questions.

The analysis identifies **where users drop out of the purchasing journey and which customer, product, device, geographic, and traffic-source patterns are associated with purchasing behavior**.

The project does not assume causation from observed patterns. Further investigation would be required to determine why specific drop-offs occur.

---

# 2. Dataset

## 2.1 Data Source

The project uses Google's public GA4 sample e-commerce dataset:

```text
bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*
```

The dataset contains e-commerce events generated by users interacting with an online store.

Examples of events include:

* `page_view`
* `view_item`
* `add_to_cart`
* `begin_checkout`
* `add_shipping_info`
* `add_payment_info`
* `purchase`

The original dataset contains nested product information inside the `items` array.

This nested structure required the use of `UNNEST()` in BigQuery to analyze product-level activity such as product views, add-to-cart events, quantities, prices, brands, and categories.

## 2.2 Analysis Period

The analysis covers:

**November 1, 2020 to January 31, 2021**

This period was used consistently throughout the project when analyzing the available e-commerce activity.

## 2.3 Dataset Structure

The original GA4 dataset is event-based. Each row represents an event associated with a user interaction.

The project therefore separates the data into different analytical layers:

* **Event-level data:** user activity and funnel events
* **Product-level data:** product views, add-to-cart activity, product attributes, prices, brands, and categories
* **Customer-level data:** purchasing behavior and order frequency
* **Order-level data:** completed orders and revenue
* **Order-item data:** products and quantities associated with completed orders

This structure makes it possible to analyze the same business journey from different perspectives.

---

# 3. Project Questions

The analysis was designed around the following business questions:

1. How much e-commerce activity occurred during the analyzed period?
2. How many users progressed through each stage of the purchasing funnel?
3. Where does the largest user drop-off occur?
4. How many users added products to their cart but did not complete a purchase?
5. How many users reached checkout but did not complete a purchase?
6. Which products show unusually low or high view-to-cart behavior?
7. Is product price associated with view-to-cart conversion?
8. Do device types show meaningful differences in product conversion?
9. Do brands show differences in view-to-cart behavior?
10. Which traffic sources are associated with the most recorded purchasing revenue?
11. How frequently do customers make repeat purchases?
12. How does customer revenue differ between one-time and repeat customers?
13. Which products and geographic markets contribute significant recorded revenue?
14. What potential revenue-recovery opportunities can be identified from the data?

These questions guide the exploration, data preparation, modeling, and business analysis stages of the project.

# 3. Data Exploration

Before cleaning or modeling the data, I explored the raw dataset to understand:

1. The date range
2. The number of events
3. The number of users
4. The main e-commerce events
5. Purchase data quality
6. The structure of product information

This step was important because I wanted to understand the data before making any transformations.

---

## 3.1 Dataset Date Range

### Business Question

**What period of time does the dataset cover?**

### SQL Query

```sql
SELECT
  MIN(PARSE_DATE('%Y%m%d', event_date)) AS start_date,
  MAX(PARSE_DATE('%Y%m%d', event_date)) AS end_date,
  COUNT(DISTINCT event_date) AS total_active_days
FROM
  `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*`;
```

### Simple Explanation

**English:**

I converted the `event_date` field from text into a real date and used `MIN()` and `MAX()` to find the first and last dates available in the dataset.

**Français :**

J'ai converti `event_date` d'un texte en vraie date, puis j'ai utilisé `MIN()` et `MAX()` pour trouver la première et la dernière date disponibles dans le dataset.

### Result

The dataset covers:

**November 1, 2020 to January 31, 2021**

### Interpretation

The dataset contains approximately three months of e-commerce activity.

### Business Insight

Knowing the time period is important because all business conclusions must be interpreted within this specific period.

### Interview Explanation

> "I first checked the date range so I knew exactly what period my analysis represented before calculating any business metrics."

---

# 3.2 Event Volume by Event Type

### Business Question

**What types of events are present in the dataset and how frequently do they occur?**

### SQL Query

```sql
SELECT
  event_name,
  COUNT(*) AS total_events,
  COUNT(DISTINCT user_pseudo_id) AS unique_users
FROM
  `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*`
GROUP BY
  event_name
ORDER BY
  total_events DESC;
```

### Simple Explanation

**English:**

I grouped the data by `event_name` to count how many times each event occurred.

I also counted distinct users to understand how many users participated in each type of activity.

**Français :**

J'ai regroupé les données par `event_name` afin de compter combien de fois chaque événement s'est produit.

J'ai également compté les utilisateurs uniques pour savoir combien d'utilisateurs ont effectué chaque type d'action.

### Result

| Event               | Total Events | Unique Users |
| ------------------- | -----------: | -----------: |
| page_view           |    1,350,428 |      269,792 |
| user_engagement     |    1,058,721 |      213,004 |
| scroll              |      493,072 |      138,098 |
| view_item           |      386,068 |       61,252 |
| session_start       |      354,970 |      267,116 |
| first_visit         |      257,462 |      257,314 |
| view_promotion      |      190,104 |      102,443 |
| add_to_cart         |       58,543 |       12,545 |
| begin_checkout      |       38,757 |        9,715 |
| select_item         |       31,007 |       13,180 |
| view_search_results |       26,172 |       14,449 |
| add_shipping_info   |       19,722 |        9,714 |
| add_payment_info    |       13,899 |        5,751 |
| select_promotion    |        9,450 |        8,164 |
| purchase            |        5,692 |        4,419 |
| click               |        1,446 |        1,010 |
| view_item_list      |           71 |           44 |

### Key Metrics

* **Total events:** 4,295,584
* **Unique users:** 270,154
* **Average events per user:** 15.90

### Interpretation

The dataset contains substantially more browsing and engagement events than purchase events, showing that purchase activity represents a much smaller portion of overall website activity.

Because event counts do not show how individual users progressed through the purchasing journey, a later user-level funnel analysis was required to measure conversion and drop-off between stages.

### Business Insight

The difference between engagement and purchase activity made the shopping funnel an important area for further investigation.

### Interview Explanation

> "The event exploration showed me that there was a large gap between user engagement and completed purchases, so I decided to investigate the e-commerce funnel."

---

# 3.3 Main E-Commerce Funnel Events

### Business Question

**How many events occur at each major stage of the shopping journey?**

### SQL Query

```sql
SELECT
  event_name,
  COUNT(*) AS event_count
FROM
  `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*`
WHERE
  event_name IN (
    'view_item',
    'add_to_cart',
    'begin_checkout',
    'purchase'
  )
GROUP BY
  event_name
ORDER BY
  CASE event_name
    WHEN 'view_item' THEN 1
    WHEN 'add_to_cart' THEN 2
    WHEN 'begin_checkout' THEN 3
    WHEN 'purchase' THEN 4
  END;
```

### Result

| Funnel Event   | Event Count |
| -------------- | ----------: |
| view_item      |     386,068 |
| add_to_cart    |      58,543 |
| begin_checkout |      38,757 |
| purchase       |       5,692 |

### Interpretation

The number of events decreases significantly as users move through the purchasing process.

However, event counts alone do not tell us how many **unique users** successfully moved from one stage to another.

For that reason, a user-level funnel analysis was required later to measure conversion and drop-off more accurately.

### Business Insight

The initial event counts suggested that there may be significant drop-off throughout the shopping journey. This made the funnel a key area for deeper analysis using unique users rather than event counts.

### Interview Explanation

> "I started by looking at the main funnel events, but I knew event counts could include multiple actions from the same user. So, I later used distinct users to measure the actual conversion between funnel stages."

---

# 3.4 Purchase Data Quality

### Business Question

**How complete is the purchase information in the raw dataset?**

### SQL Query

```sql
SELECT
  COUNT(*) AS total_purchase_events,
  COUNTIF(ecommerce.transaction_id IS NOT NULL)
    AS purchases_with_transaction_id,
  COUNTIF(ecommerce.transaction_id IS NULL)
    AS purchases_without_transaction_id,
  COUNTIF(ecommerce.purchase_revenue IS NOT NULL)
    AS purchases_with_revenue,
  COUNTIF(ecommerce.purchase_revenue IS NULL)
    AS purchases_without_revenue
FROM
  `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*`
WHERE
  event_name = 'purchase';
```

### Simple Explanation

**English:**

I checked whether purchase events had important fields such as transaction IDs and revenue.

A transaction ID helps identify an individual transaction, while purchase revenue tells us the value associated with the purchase.

**Français :**

J'ai vérifié si les événements d'achat contenaient des informations importantes comme l'identifiant de transaction et le revenu.

L'identifiant de transaction permet d'identifier une transaction individuelle, tandis que le revenu d'achat indique la valeur associée à cet achat.

### Result

| Metric                 | Result |
| ---------------------- | -----: |
| Total purchase events  |  5,692 |
| With transaction ID    |  5,669 |
| Without transaction ID |     23 |
| With revenue           |  5,242 |
| Without revenue        |    450 |

### Interpretation

Most purchase events contain a transaction ID, but **23 purchase events have a missing transaction ID**.

Revenue is also missing from **450 purchase events**.

These missing values do not mean that the entire dataset is unusable, but they need to be considered when calculating transactions and revenue.

### Business Insight

These missing values were considered during the data-cleaning and data-modeling stages because incomplete transaction identifiers or revenue values can affect transaction counting, deduplication, and revenue calculations.

### Interview Explanation

> "Before creating my order table, I checked the quality of the transaction and revenue fields because missing identifiers can affect deduplication and revenue analysis."

---

# 3.5 Product Data Structure

### Business Question

**How is product information stored in the raw GA4 dataset?**

### SQL Query

```sql
SELECT
  event_name,
  COUNT(*) AS total_item_records
FROM
  `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*`,
  UNNEST(items) AS item
WHERE
  event_name IN (
    'view_item',
    'add_to_cart',
    'begin_checkout',
    'purchase'
  )
GROUP BY
  event_name;
```

### Simple Explanation

**English:**

The `items` field is a nested array. This means that product information is stored inside each e-commerce event rather than in separate rows.

I used `UNNEST()` to turn the products inside the array into individual rows.

This made it possible to analyze individual products and their attributes.

**Français :**

Le champ `items` est un tableau de données imbriquées. Cela signifie que les informations sur les produits sont stockées à l'intérieur de chaque événement e-commerce plutôt que dans des lignes séparées.

J'ai utilisé `UNNEST()` pour transformer les produits contenus dans ce tableau en lignes individuelles.

Cela m'a permis d'analyser les produits individuellement ainsi que leurs caractéristiques.

### Result

| Event          | Product Item Records |
| -------------- | -------------------: |
| view_item      |            2,748,246 |
| add_to_cart    |              667,426 |
| begin_checkout |               77,980 |
| purchase       |               16,003 |

### Interpretation

One e-commerce event can contain multiple products.

Therefore, the event-level data alone is not sufficient for detailed product analysis. The nested `items` array had to be flattened so that each product could be analyzed as an individual record.

### Business Insight

The nested product structure meant that product analysis required an additional transformation.

Flattening the `items` array made it possible to analyze:

* Individual products
* Product prices
* Brands
* Categories
* Product quantities
* Product-level customer interactions
* Product behavior across the shopping funnel

This became an important step in preparing the data for product-level analysis.

### Interview Explanation

> "I discovered that product information was stored inside a nested `items` array. I used `UNNEST()` to flatten that data so I could analyze individual products and connect product behavior to the shopping funnel."

---

# Section 3 Summary

The initial exploration provided several important findings before the data-cleaning stage:

* The dataset covers **November 1, 2020 to January 31, 2021**.
* It contains **4,295,584 events** from **270,154 unique users**.
* Browsing and engagement events are much more common than purchase events.
* The main purchasing journey includes product views, add-to-cart, checkout, and purchase.
* **5,692 purchase events** were recorded, with some missing transaction IDs and revenue values.
* Product information is stored in a nested `items` array and requires `UNNEST()` for product-level analysis.
* These findings helped determine what needed to be addressed during the data-cleaning and modeling stages.

### Overall Interview Explanation

> "I started my project by exploring the raw GA4 dataset before changing anything. I checked the date range, event volume, user activity, funnel events, purchase data quality, and the structure of the product information. This helped me understand the dataset and identify potential data-quality issues. I also discovered that product information was nested inside an `items` array, so I knew I would need to flatten that data before performing detailed product analysis. After this exploration, I moved into the data-cleaning stage."

---

# 4. Data Cleaning

The raw GA4 data contains useful information, but it is stored in a nested event structure and is not yet organized for efficient business analysis.

The cleaning process prepares the raw data into structured tables that separate:

1. Event-level information for customer and funnel analysis
2. Product-level information for product and shopping-behavior analysis

The main cleaned tables created during this stage are:

* `cleaned_events`
* `cleaned_event_items`

The cleaning process also includes data-quality checks for missing user identifiers, invalid product names, missing transaction IDs, duplicate purchase events, and revenue consistency.

---

# 4.1 Cleaned Events Table

### Purpose

The `cleaned_events` table contains event-level information needed for customer behavior, funnel, device, geographic, and transaction analysis.

### SQL Query

```sql
CREATE OR REPLACE TABLE
  `e-commerce-revenue-recovery.ecommerce_analytics.cleaned_events` AS

SELECT
  PARSE_DATE('%Y%m%d', event_date) AS event_date,
  event_timestamp,
  event_name,
  user_pseudo_id,
  user_id,
  platform,
  device.category AS device_category,
  device.operating_system AS operating_system,
  device.web_info.browser AS browser,
  geo.country AS country,
  geo.city AS city,
  ecommerce.transaction_id AS transaction_id,
  ecommerce.purchase_revenue AS purchase_revenue,
  ecommerce.total_item_quantity AS total_item_quantity,
  ecommerce.unique_items AS unique_items

FROM
  `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*`

WHERE
  user_pseudo_id IS NOT NULL;
```

### Simple Explanation

**English:**

I selected the fields needed for customer and funnel analysis instead of carrying the entire raw event structure forward.

I converted `event_date` from a text value into a proper `DATE`.

I also kept useful information about the user, device, location, transaction, and purchase.

Finally, I excluded rows where `user_pseudo_id` was missing because the project relies heavily on user-level analysis.

**Français :**

J'ai sélectionné les champs nécessaires à l'analyse des utilisateurs et du funnel au lieu de conserver toute la structure brute.

J'ai converti `event_date`, qui était sous forme de texte, en véritable type `DATE`.

J'ai également conservé les informations utiles concernant l'utilisateur, l'appareil, la localisation, la transaction et l'achat.

Enfin, j'ai exclu les lignes où `user_pseudo_id` était absent, car le projet repose principalement sur l'analyse du comportement des utilisateurs.

### Interpretation

The raw event data was reduced to the fields needed for the main user-level analysis.

This created a simpler analytical table while preserving the information required for funnel, customer, device, geographic, and transaction analysis.

### Business Insight

Creating a focused event-level table makes later SQL analysis easier to read, maintain, and reuse.

Instead of repeatedly working with the full nested GA4 structure, the analysis can use `cleaned_events` as a standardized event-level dataset.

### Interview Explanation

> "I created a cleaned event-level table containing the fields needed for my analysis. I converted the date into a proper DATE type, extracted useful device and geographic fields, and removed records without a user identifier because my funnel analysis depends on identifying users."

---

# 4.2 Cleaned Event Items Table

### Purpose

The `cleaned_event_items` table contains product-level information extracted from the nested `items` array.

This table allows individual products to be analyzed across the main e-commerce funnel.

### SQL Query

```sql
CREATE OR REPLACE TABLE
  `e-commerce-revenue-recovery.ecommerce_analytics.cleaned_event_items` AS

SELECT
  PARSE_DATE('%Y%m%d', event_date) AS event_date,
  event_timestamp,
  event_name,
  user_pseudo_id,
  ecommerce.transaction_id AS transaction_id,
  items.item_id AS item_id,
  items.item_name AS item_name,
  items.quantity AS quantity,
  items.price AS price

FROM
  `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*`,
  UNNEST(items) AS items

WHERE
  user_pseudo_id IS NOT NULL
  AND event_name IN (
    'view_item',
    'add_to_cart',
    'begin_checkout',
    'purchase'
  )
  AND items.item_name IS NOT NULL
  AND items.item_name != '(not set)';
```

### Simple Explanation

**English:**

The product information is stored inside the nested `items` array.

I used `UNNEST(items)` to flatten this array so that each product becomes its own row.

I kept the transaction ID because it can later be used to connect product records with transactions and orders.

I also removed records where the product name was missing or equal to `(not set)`.

**Français :**

Les informations sur les produits sont stockées dans le tableau imbriqué `items`.

J'ai utilisé `UNNEST(items)` pour transformer ce tableau en lignes individuelles afin que chaque produit puisse être analysé séparément.

J'ai conservé le `transaction_id` afin de pouvoir relier plus tard les produits aux transactions et aux commandes.

J'ai également supprimé les lignes où le nom du produit était absent ou égal à `(not set)`.

### Interpretation

Flattening the `items` array transformed nested product information into a row-level structure that could be analyzed using standard SQL.

The resulting table can be used to study product views, add-to-cart behavior, checkout activity, purchases, prices, quantities, and product-level conversion patterns.

### Business Insight

The product-level table was necessary because the main event table does not provide enough detail for product analysis.

Separating event-level and product-level information also makes the analytical workflow easier to manage.

### Interview Explanation

> "The raw GA4 data stored products inside a nested items array. I used UNNEST to flatten the product information, then created a separate product-event table so I could analyze individual products across the shopping funnel."

---

# 4.3 Product Data Reconciliation

### Purpose

After flattening the product data, I compared the number of product records before and after applying the product-name quality filter.

### Result

The main funnel product records before removing invalid product names contained:

**3,509,655 rows**

Invalid product-name rows:

**2,534 rows**

The expected number of remaining rows was therefore:

```text
3,509,655 - 2,534 = 3,507,121
```

The final `cleaned_event_items` table contains:

**3,507,121 rows**

### Interpretation

The number of rows after cleaning matches the expected calculation.

This confirms that the filter removing null or `(not set)` product names worked as expected.

### Business Insight

Reconciliation checks are useful because they confirm that a cleaning step changed the data in the expected way rather than unintentionally removing additional records.

### Interview Explanation

> "After filtering invalid product names, I reconciled the row counts before and after cleaning. The calculation matched the final table, which gave me confidence that the filtering step behaved as expected."

---

# 4.4 Missing Transaction IDs

### Business Question

**How many cleaned product records are associated with a transaction ID, and how many are missing one?**

### Result

| Metric                      |    Result |
| --------------------------- | --------: |
| Total cleaned item rows     | 3,507,121 |
| Rows with transaction ID    | 3,481,779 |
| Rows without transaction ID |    25,342 |

### Investigation

The missing transaction IDs are mainly associated with `view_item` events.

A further investigation of purchase events found:

* **November 1, 2020:** 14 purchase events without transaction IDs
* **November 2, 2020:** 9 purchase events without transaction IDs

These purchase events still contained product information and revenue.

### Interpretation

The missing transaction IDs originate from the source data rather than being introduced by the cleaning process.

The product records can still be useful for event-level and product-level analysis even when a transaction ID is unavailable.

However, a valid transaction ID is important when building transaction-based analytical tables such as `orders` and `order_items`.

### Decision

The records were retained in `cleaned_event_items` because removing them would discard potentially useful product and behavioral information.

However, transaction-based analysis uses valid transaction identifiers where required.

### Business Insight

This distinction is important because **not every useful product record needs to belong to a completed transaction**.

For example, a `view_item` event can provide valuable information about product interest even when there is no transaction ID.

### Interview Explanation

> "I found that some product records did not have transaction IDs, especially product-view events. I kept those records because they are still useful for behavioral analysis. However, when building transaction-based tables, I only relied on valid transaction identifiers."

---

# 4.5 Invalid Product Names

### Business Question

**Are there product records that do not contain meaningful product names?**

### Data Quality Issue

Some product records contain:

```text
(not set)
```

This value does not represent an actual product name.

### Cleaning Decision

Records with:

```text
item_name IS NULL
```

or:

```text
item_name = '(not set)'
```

were excluded from `cleaned_event_items`.

### Interpretation

Keeping invalid product names could cause these records to appear in product rankings, conversion analysis, or other product-level reports.

Removing them makes the product-level analysis more meaningful.

### Business Insight

This cleaning step prevents placeholder values from being treated as real products.

### Interview Explanation

> "I identified `(not set)` as a placeholder rather than a meaningful product name, so I excluded those records from product-level analysis to avoid misleading results."

---

# 4.6 Data Quality Checks

The cleaning process included several checks to make sure the analytical tables were reliable.

### Checks Performed

**1. Missing User IDs**

Rows without `user_pseudo_id` were excluded because user-level analysis requires a user identifier.

**2. Invalid Product Names**

Null product names and `(not set)` values were excluded from the product-level table.

**3. Missing Transaction IDs**

Missing transaction IDs were investigated rather than automatically deleting the records.

**4. Duplicate Purchase Events**

Purchase records were checked because duplicate events could affect transaction and revenue calculations.

**5. Revenue Consistency**

Purchase revenue was reviewed to identify missing or inconsistent revenue values before transaction-level analysis.

### Interpretation

The cleaning process was not simply about deleting missing values.

Each data-quality issue was evaluated according to how the field would be used later in the project.

For example:

* A missing user ID affects user-level analysis.
* A missing product name affects product-level analysis.
* A missing transaction ID affects transaction-level analysis.
* Missing revenue affects revenue calculations.

### Business Insight

Different types of missing data can have different effects on an analysis.

Therefore, I did not apply one rule to every missing value. Instead, I considered the purpose of each field before deciding whether to exclude, retain, or investigate the record.

### Interview Explanation

> "During cleaning, I did not automatically remove every row containing a missing value. I looked at what each field was used for. For example, missing user IDs could not support user-level analysis, while a product record without a transaction ID could still be useful for product-view analysis. This helped me make cleaning decisions based on the analytical purpose of each field."

---

# Section 4 Summary

The data-cleaning stage transformed the raw GA4 event structure into more usable analytical tables.

The main cleaning steps were:

* Converted `event_date` into a proper `DATE`
* Selected relevant event-level fields
* Removed records without `user_pseudo_id`
* Flattened the nested `items` array using `UNNEST()`
* Created product-level records for the main funnel events
* Removed null and `(not set)` product names
* Reconciled product row counts after filtering
* Investigated missing transaction IDs
* Checked purchase-event and revenue data quality
* Prepared the data for later modeling and business analysis

### Overall Interview Explanation

> "After exploring the raw data, I moved into cleaning. I created a structured event-level table and a product-level table. I converted the date field, selected the fields needed for analysis, removed records without user identifiers, and used UNNEST to flatten the nested product data. I also investigated missing transaction IDs and invalid product names rather than treating every missing value the same way. Finally, I performed reconciliation and data-quality checks to make sure the cleaning process produced the expected results. This prepared the dataset for the data-modeling and business-analysis stages."

---
 # 4. Data Cleaning

The raw GA4 data contains useful information, but it is stored in a nested event structure and is not yet organized for efficient business analysis.

The cleaning process prepares the raw data into structured tables that separate:

1. Event-level information for customer and funnel analysis
2. Product-level information for product and shopping-behavior analysis

The main cleaned tables created during this stage are:

* `cleaned_events`
* `cleaned_event_items`

The cleaning process also includes data-quality checks for missing user identifiers, invalid product names, missing transaction IDs, duplicate purchase events, and revenue consistency.

---

# 4.1 Cleaned Events Table

### Purpose

The `cleaned_events` table contains event-level information needed for customer behavior, funnel, device, geographic, and transaction analysis.

### SQL Query

```sql
CREATE OR REPLACE TABLE
  `e-commerce-revenue-recovery.ecommerce_analytics.cleaned_events` AS

SELECT
  PARSE_DATE('%Y%m%d', event_date) AS event_date,
  event_timestamp,
  event_name,
  user_pseudo_id,
  user_id,
  platform,
  device.category AS device_category,
  device.operating_system AS operating_system,
  device.web_info.browser AS browser,
  geo.country AS country,
  geo.city AS city,
  ecommerce.transaction_id AS transaction_id,
  ecommerce.purchase_revenue AS purchase_revenue,
  ecommerce.total_item_quantity AS total_item_quantity,
  ecommerce.unique_items AS unique_items

FROM
  `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*`

WHERE
  user_pseudo_id IS NOT NULL;
```

### Simple Explanation

**English:**

I selected the fields needed for customer and funnel analysis instead of carrying the entire raw event structure forward.

I converted `event_date` from a text value into a proper `DATE`.

I also kept useful information about the user, device, location, transaction, and purchase.

Finally, I excluded rows where `user_pseudo_id` was missing because the project relies heavily on user-level analysis.

**Français :**

J'ai sélectionné les champs nécessaires à l'analyse des utilisateurs et du funnel au lieu de conserver toute la structure brute.

J'ai converti `event_date`, qui était sous forme de texte, en véritable type `DATE`.

J'ai également conservé les informations utiles concernant l'utilisateur, l'appareil, la localisation, la transaction et l'achat.

Enfin, j'ai exclu les lignes où `user_pseudo_id` était absent, car le projet repose principalement sur l'analyse du comportement des utilisateurs.

### Interpretation

The raw event data was reduced to the fields needed for the main user-level analysis.

This created a simpler analytical table while preserving the information required for funnel, customer, device, geographic, and transaction analysis.

### Business Insight

Creating a focused event-level table makes later SQL analysis easier to read, maintain, and reuse.

Instead of repeatedly working with the full nested GA4 structure, the analysis can use `cleaned_events` as a standardized event-level dataset.

### Interview Explanation

> "I created a cleaned event-level table containing the fields needed for my analysis. I converted the date into a proper DATE type, extracted useful device and geographic fields, and removed records without a user identifier because my funnel analysis depends on identifying users."

---

# 4.2 Cleaned Event Items Table

### Purpose

The `cleaned_event_items` table contains product-level information extracted from the nested `items` array.

This table allows individual products to be analyzed across the main e-commerce funnel.

### SQL Query

```sql
CREATE OR REPLACE TABLE
  `e-commerce-revenue-recovery.ecommerce_analytics.cleaned_event_items` AS

SELECT
  PARSE_DATE('%Y%m%d', event_date) AS event_date,
  event_timestamp,
  event_name,
  user_pseudo_id,
  ecommerce.transaction_id AS transaction_id,
  items.item_id AS item_id,
  items.item_name AS item_name,
  items.quantity AS quantity,
  items.price AS price

FROM
  `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*`,
  UNNEST(items) AS items

WHERE
  user_pseudo_id IS NOT NULL
  AND event_name IN (
    'view_item',
    'add_to_cart',
    'begin_checkout',
    'purchase'
  )
  AND items.item_name IS NOT NULL
  AND items.item_name != '(not set)';
```

### Simple Explanation

**English:**

The product information is stored inside the nested `items` array.

I used `UNNEST(items)` to flatten this array so that each product becomes its own row.

I kept the transaction ID because it can later be used to connect product records with transactions and orders.

I also removed records where the product name was missing or equal to `(not set)`.

**Français :**

Les informations sur les produits sont stockées dans le tableau imbriqué `items`.

J'ai utilisé `UNNEST(items)` pour transformer ce tableau en lignes individuelles afin que chaque produit puisse être analysé séparément.

J'ai conservé le `transaction_id` afin de pouvoir relier plus tard les produits aux transactions et aux commandes.

J'ai également supprimé les lignes où le nom du produit était absent ou égal à `(not set)`.

### Interpretation

Flattening the `items` array transformed nested product information into a row-level structure that could be analyzed using standard SQL.

The resulting table can be used to study product views, add-to-cart behavior, checkout activity, purchases, prices, quantities, and product-level conversion patterns.

### Business Insight

The product-level table was necessary because the main event table does not provide enough detail for product analysis.

Separating event-level and product-level information also makes the analytical workflow easier to manage.

### Interview Explanation

> "The raw GA4 data stored products inside a nested items array. I used UNNEST to flatten the product information, then created a separate product-event table so I could analyze individual products across the shopping funnel."

---

# 4.3 Product Data Reconciliation

### Purpose

After flattening the product data, I compared the number of product records before and after applying the product-name quality filter.

### Result

The main funnel product records before removing invalid product names contained:

**3,509,655 rows**

Invalid product-name rows:

**2,534 rows**

The expected number of remaining rows was therefore:

```text
3,509,655 - 2,534 = 3,507,121
```

The final `cleaned_event_items` table contains:

**3,507,121 rows**

### Interpretation

The number of rows after cleaning matches the expected calculation.

This confirms that the filter removing null or `(not set)` product names worked as expected.

### Business Insight

Reconciliation checks are useful because they confirm that a cleaning step changed the data in the expected way rather than unintentionally removing additional records.

### Interview Explanation

> "After filtering invalid product names, I reconciled the row counts before and after cleaning. The calculation matched the final table, which gave me confidence that the filtering step behaved as expected."

---

# 4.4 Missing Transaction IDs

### Business Question

**How many cleaned product records are associated with a transaction ID, and how many are missing one?**

### Result

| Metric                      |    Result |
| --------------------------- | --------: |
| Total cleaned item rows     | 3,507,121 |
| Rows with transaction ID    | 3,481,779 |
| Rows without transaction ID |    25,342 |

### Investigation

The missing transaction IDs are mainly associated with `view_item` events.

A further investigation of purchase events found:

* **November 1, 2020:** 14 purchase events without transaction IDs
* **November 2, 2020:** 9 purchase events without transaction IDs

These purchase events still contained product information and revenue.

### Interpretation

The missing transaction IDs originate from the source data rather than being introduced by the cleaning process.

The product records can still be useful for event-level and product-level analysis even when a transaction ID is unavailable.

However, a valid transaction ID is important when building transaction-based analytical tables such as `orders` and `order_items`.

### Decision

The records were retained in `cleaned_event_items` because removing them would discard potentially useful product and behavioral information.

However, transaction-based analysis uses valid transaction identifiers where required.

### Business Insight

This distinction is important because **not every useful product record needs to belong to a completed transaction**.

For example, a `view_item` event can provide valuable information about product interest even when there is no transaction ID.

### Interview Explanation

> "I found that some product records did not have transaction IDs, especially product-view events. I kept those records because they are still useful for behavioral analysis. However, when building transaction-based tables, I only relied on valid transaction identifiers."

---

# 4.5 Invalid Product Names

### Business Question

**Are there product records that do not contain meaningful product names?**

### Data Quality Issue

Some product records contain:

```text
(not set)
```

This value does not represent an actual product name.

### Cleaning Decision

Records with:

```text
item_name IS NULL
```

or:

```text
item_name = '(not set)'
```

were excluded from `cleaned_event_items`.

### Interpretation

Keeping invalid product names could cause these records to appear in product rankings, conversion analysis, or other product-level reports.

Removing them makes the product-level analysis more meaningful.

### Business Insight

This cleaning step prevents placeholder values from being treated as real products.

### Interview Explanation

> "I identified `(not set)` as a placeholder rather than a meaningful product name, so I excluded those records from product-level analysis to avoid misleading results."

---

# 4.6 Data Quality Checks

The cleaning process included several checks to make sure the analytical tables were reliable.

### Checks Performed

**1. Missing User IDs**

Rows without `user_pseudo_id` were excluded because user-level analysis requires a user identifier.

**2. Invalid Product Names**

Null product names and `(not set)` values were excluded from the product-level table.

**3. Missing Transaction IDs**

Missing transaction IDs were investigated rather than automatically deleting the records.

**4. Duplicate Purchase Events**

Purchase records were checked because duplicate events could affect transaction and revenue calculations.

**5. Revenue Consistency**

Purchase revenue was reviewed to identify missing or inconsistent revenue values before transaction-level analysis.

### Interpretation

The cleaning process was not simply about deleting missing values.

Each data-quality issue was evaluated according to how the field would be used later in the project.

For example:

* A missing user ID affects user-level analysis.
* A missing product name affects product-level analysis.
* A missing transaction ID affects transaction-level analysis.
* Missing revenue affects revenue calculations.

### Business Insight

Different types of missing data can have different effects on an analysis.

Therefore, I did not apply one rule to every missing value. Instead, I considered the purpose of each field before deciding whether to exclude, retain, or investigate the record.

### Interview Explanation

> "During cleaning, I did not automatically remove every row containing a missing value. I looked at what each field was used for. For example, missing user IDs could not support user-level analysis, while a product record without a transaction ID could still be useful for product-view analysis. This helped me make cleaning decisions based on the analytical purpose of each field."

---

# Section 4 Summary

The data-cleaning stage transformed the raw GA4 event structure into more usable analytical tables.

The main cleaning steps were:

* Converted `event_date` into a proper `DATE`
* Selected relevant event-level fields
* Removed records without `user_pseudo_id`
* Flattened the nested `items` array using `UNNEST()`
* Created product-level records for the main funnel events
* Removed null and `(not set)` product names
* Reconciled product row counts after filtering
* Investigated missing transaction IDs
* Checked purchase-event and revenue data quality
* Prepared the data for later modeling and business analysis

### Overall Interview Explanation

> "After exploring the raw data, I moved into cleaning. I created a structured event-level table and a product-level table. I converted the date field, selected the fields needed for analysis, removed records without user identifiers, and used UNNEST to flatten the nested product data. I also investigated missing transaction IDs and invalid product names rather than treating every missing value the same way. Finally, I performed reconciliation and data-quality checks to make sure the cleaning process produced the expected results. This prepared the dataset for the data-modeling and business-analysis stages."

# 9. Business Analysis

The next stage of the project focuses on answering business questions using the analytical model created during the data-modeling stage.

The main business problem is:

> **Where are customers dropping out of the shopping journey, and where could the business potentially recover lost revenue?**

The analysis focuses on the customer funnel, product behavior, customer purchasing patterns, traffic sources, and potential revenue recovery opportunities.

---

# 9.1 Funnel Analysis

### Business Question

**Where do customers leave the shopping funnel?**

The funnel was analyzed using unique users recorded at each e-commerce event stage.

### Funnel

```text
View Item
61,252 users
      ↓
Add to Cart
12,545 users
      ↓
Begin Checkout
9,715 users
      ↓
Add Shipping Info
9,714 users
      ↓
Add Payment Info
5,751 users
      ↓
Purchase
4,419 users
```

### Funnel Results

| Funnel Stage      | Unique Users |
| ----------------- | -----------: |
| View Item         |       61,252 |
| Add to Cart       |       12,545 |
| Begin Checkout    |        9,715 |
| Add Shipping Info |        9,714 |
| Add Payment Info  |        5,751 |
| Purchase          |        4,419 |

---

# 9.2 Funnel Conversion Rates

### View Item → Add to Cart

Conversion rate:

**20.48%**

Drop-off:

**79.52%**

Users not progressing to the next stage:

**48,707**

This represents the largest numerical drop in the funnel.

### Add to Cart → Begin Checkout

Conversion rate:

**77.44%**

Drop-off:

**22.56%**

Users not progressing to checkout:

**2,830**

### Begin Checkout → Add Shipping Info

Conversion rate:

**99.99%**

Drop-off:

Approximately **0.01%**

Users not progressing to shipping information:

**1**

### Add Shipping Info → Add Payment Info

Conversion rate:

**59.20%**

Drop-off:

**40.80%**

Users not progressing to payment information:

**3,963**

### Add Payment Info → Purchase

Conversion rate:

**76.84%**

Drop-off:

**23.16%**

Users not progressing to purchase:

**1,332**

### Begin Checkout → Purchase

The conversion rate from checkout to purchase was:

**45.49%**

This provides an additional view of how many checkout users eventually recorded a purchase event.

---

# 9.3 Funnel Interpretation

The largest numerical drop occurs between:

```text
View Item
    ↓
Add to Cart
```

Only **20.48%** of users who recorded a product view also recorded an add-to-cart event.

A second significant drop occurs between:

```text
Add Shipping Info
    ↓
Add Payment Info
```

The conversion rate at this stage was **59.20%**.

### Business Insight

The funnel highlights two important areas for further investigation:

1. Product engagement and the decision to add products to the cart.
2. The transition from shipping information to payment information.

These patterns may represent opportunities for conversion optimization and potential revenue recovery.

However, the event data shows **where users dropped out**, not necessarily **why** they dropped out. Additional analysis would be required to identify the underlying causes.

---

# 9.4 Overall Item-View-to-Purchase Conversion

The analysis identified:

* **61,252** unique users who recorded a product view
* **4,419** unique users who recorded a purchase event

The resulting item-view-to-purchase conversion was:

**7.21%**

### Calculation

```text
4,419 ÷ 61,252 × 100 = 7.21%
```

### Interpretation

Approximately **7.21% of users who recorded a product view also recorded a purchase event** during the analyzed period.

This metric should be interpreted as a user-level event relationship rather than proof that every user followed the funnel stages in a perfectly sequential order.

---

# 9.5 Funnel Data Quality Note

The funnel stages are based on distinct users associated with each event.

Because the dataset contains event-level tracking data, a user can appear at one stage without necessarily appearing at every previous stage in a perfectly chronological sequence.

For example, the analysis identified **5,751 users with an `add_payment_info` event**, while **5,750 of those users also appeared among users who recorded `begin_checkout`**.

This small difference indicates that event tracking is not perfectly sequential for every user.

Therefore, the funnel should be used to identify **patterns and areas for investigation**, rather than interpreted as a perfectly closed experimental conversion funnel.

---

# 10. Product Performance Analysis

Product-level analysis was used to identify which products attract attention, which products generate add-to-cart activity, and which products show unusually low conversion from viewing to adding to cart.

---

# 10.1 Top Products by Views

### Business Question

**Which products receive the most product views?**

Products with null names or the value `(not set)` were excluded.

### Top Products

| Product                  | Unique Viewers |
| ------------------------ | -------------: |
| Super G Unisex Joggers   |         14,713 |
| Google Zip Hoodie F/C    |         13,869 |
| Google Navy Speckled Tee |         13,696 |

### Interpretation

These products attracted substantial attention from users.

However, high product views do not automatically indicate high sales performance.

A product can receive significant traffic while having a relatively low add-to-cart rate.

---

# 10.2 Top Products by Add-to-Cart Users

### Business Question

**Which products are most frequently added to carts?**

### Top Products

| Product                      | Unique Adders |
| ---------------------------- | ------------: |
| Google Land & Sea Cotton Cap |         3,569 |
| Google Zip Hoodie F/C        |         3,539 |
| Google Navy Speckled Tee     |         3,527 |

### Interpretation

These products generated strong add-to-cart activity.

Comparing product views with add-to-cart users provides a better understanding of product-level conversion behavior than looking at views alone.

---

# 10.3 Products with Low View-to-Cart Conversion

To avoid focusing on products with very little traffic, the analysis considered products with at least **1,000 unique viewers**.

The lowest observed view-to-cart rates included:

| Product                                | Viewers | Adders | View-to-Cart Rate |
| -------------------------------------- | ------: | -----: | ----------------: |
| Google Tracking Hat                    |   1,414 |      0 |             0.00% |
| Google Campus Bike                     |   1,986 |    150 |             7.55% |
| Google Tonal Tee Spearmint             |   1,134 |     94 |             8.29% |
| Google Incognito Zip Pack              |   1,419 |    140 |             9.87% |
| Candy Cane Android Cardboard Sculpture |   2,275 |    281 |            12.35% |

### Interpretation

These products received meaningful levels of product attention but had relatively low rates of recorded add-to-cart activity.

This makes them useful candidates for further investigation.

The analysis does not establish why users did not add these products to their carts. Possible explanations would require additional evidence, such as pricing, product availability, product-page experience, or marketing context.

---

# 10.4 Google Tracking Hat Investigation

The Google Tracking Hat showed an unusual pattern.

### Observed Activity

| Event       | Event Rows | Unique Users |
| ----------- | ---------: | -----------: |
| View Item   |      2,893 |        1,414 |
| Add to Cart |          0 |            0 |

The product had:

* **1,414 unique viewers**
* **2,893 recorded product-view events**
* **0 recorded add-to-cart users**
* **0.00% view-to-cart rate**

The average number of recorded product views per viewer was approximately **2.05**.

### Interpretation

The product received repeated attention from users, but no add-to-cart activity was recorded for this product in the analyzed data.

This is an important data pattern to investigate further.

However, the analysis cannot determine whether the pattern was caused by:

* product characteristics
* pricing
* availability
* user intent
* tracking behavior
* or another factor

Therefore, the result is treated as an **observed conversion pattern**, not a causal conclusion.

---

# 10.5 Product Price and View-to-Cart Behavior

A product-level analysis was conducted to investigate whether price was associated with view-to-cart conversion.

Products with at least **1,000 unique viewers** were included.

The correlation between average product price and view-to-cart rate was:

**r = -0.222**

### Interpretation

The analysis found a **weak negative correlation** between product price and view-to-cart rate.

This means that higher-priced products tended to have somewhat lower view-to-cart rates in this dataset.

However, the relationship is weak, meaning price alone does not explain the large differences in product conversion.

This should therefore be interpreted as an association rather than evidence that price causes lower conversion.

---

# 10.6 Device Performance

The funnel was also compared across device categories.

| Device  | Viewers | Adders | Users Lost | View-to-Cart Rate |
| ------- | ------: | -----: | ---------: | ----------------: |
| Tablet  |   1,443 |    276 |      1,167 |            19.13% |
| Desktop |  36,323 |  7,384 |     28,939 |            20.33% |
| Mobile  |  24,810 |  5,142 |     19,668 |            20.73% |

### Interpretation

The view-to-cart rates were relatively close across devices:

* Tablet: **19.13%**
* Desktop: **20.33%**
* Mobile: **20.73%**

The difference between the highest and lowest rate was approximately **1.6 percentage points**.

This suggests that device category alone does not explain the large overall view-to-cart drop.

The analysis therefore provides a useful comparison, but does not establish that a particular device causes lower conversion.

---

# 11. Customer Purchase Behavior

Customer-level analysis was used to understand purchasing frequency, customer value, and differences between one-time and repeat customers.

## 11.1 Cart Users Without Recorded Purchase

The analysis identified:

**9,630 cart users without a recorded purchase event.**

This represented approximately:

**76.77% of cart users.**

### Interpretation

These users demonstrated purchase intent by adding products to their carts but did not have a recorded purchase event in the dataset.

They represent a potentially valuable audience for further revenue-recovery analysis.

However, the data does not reveal why the purchase was not completed.

---

## 11.2 Checkout Users Without Recorded Purchase

The analysis identified:

**5,296 checkout users without a recorded purchase event.**

This represented approximately:

**54.49% of checkout users.**

### Interpretation

These users progressed further into the purchasing journey than cart-only users but did not have a recorded purchase event.

This group may be particularly relevant for further investigation of checkout-stage abandonment.

---

## 11.3 Customer Purchase Frequency

Among purchasing customers:

* **3,245** customers placed one order
* **320** placed two orders
* **84** placed three orders
* Smaller numbers placed four or more orders

Total purchasing customers:

**3,713**

Repeat customers:

**468**

Repeat purchase rate:

**12.60%**

### Interpretation

Most purchasing customers placed only one order during the analyzed period.

A smaller group returned and made multiple purchases.

---

## 11.4 One-Time vs. Repeat Customer Revenue

| Customer Type | Customers |  Revenue |
| ------------- | --------: | -------: |
| One-time      |     3,245 | $230,609 |
| Repeat        |       468 |  $80,767 |

Average revenue per customer:

* One-time customers: approximately **$71.06**
* Repeat customers: approximately **$172.58**

### Interpretation

Repeat customers generated substantially more total revenue per customer during the analyzed period.

However, this does not mean that their individual orders were larger.

The difference is largely associated with repeat customers placing multiple orders.

---

## 11.5 One-Time vs. Repeat Average Order Value

| Customer Type | Orders |  Revenue | Average Order Value |
| ------------- | -----: | -------: | ------------------: |
| One-time      |  3,245 | $230,609 |              $71.07 |
| Repeat        |  1,264 |  $80,767 |              $63.90 |

### Interpretation

One-time customers had a higher average order value:

**$71.07 vs. $63.90**

Therefore, the higher total revenue per repeat customer is not explained by larger individual orders.

Instead, repeat customers generated more cumulative customer revenue because they placed multiple orders during the analyzed period.

This demonstrates the difference between:

```text
Order Value
= value of one individual order

Customer Value
= total revenue generated by a customer
```

---

# 12. Traffic Source Analysis

Traffic-source analysis was performed using the raw GA4 event data because `traffic_source` is not included in the `cleaned_events` table.

### Business Question

**Which traffic sources are associated with purchasing activity and recorded revenue?**

### Key Results

| Traffic Source                | Medium   | Purchasing Users | Transactions | Revenue |
| ----------------------------- | -------- | ---------------: | -----------: | ------: |
| Google                        | organic  |            1,229 |        1,156 | $95,775 |
| (direct)                      | (none)   |            1,054 |          970 | $79,650 |
| shop.googlemerchandystore.com | referral |              568 |          558 | $46,521 |
| Google                        | cpc      |              152 |          133 |  $9,056 |

Some traffic-source values are anonymized or grouped as `<Other>` or `(data deleted)` in the source dataset.

### Interpretation

Google organic traffic generated the highest recorded revenue among the identified traffic-source groups, followed by direct traffic.

However, revenue alone cannot determine which channel is most efficient because the dataset does not provide the marketing cost required to calculate metrics such as:

* cost per acquisition
* return on advertising spend
* customer acquisition cost

Therefore, this analysis describes recorded purchasing activity and revenue rather than channel profitability.

---

# 13. Data Quality and Analytical Limitations

Several data-quality considerations were identified throughout the project.

### User Identification

Rows without `user_pseudo_id` were excluded from the cleaned event table because user-level analysis is central to the project.

### Product Identification

Product names and product IDs were not always perfectly consistent.

Because of this, some product-level conversion analysis was performed using `item_name` rather than relying exclusively on `item_id`.

### Traffic Source

Traffic-source information exists in the raw GA4 dataset but is not included in `cleaned_events`.

Some traffic-source values are also anonymized or grouped.

### Funnel Sequencing

The funnel is based on distinct users recorded at different event stages.

Not every user necessarily followed every stage in a perfectly sequential order.

### Revenue Reconciliation

Order-level GA4 revenue and calculated product-level revenue were close but not identical.

This difference was documented rather than artificially corrected.

These limitations are important because they define what conclusions can and cannot be made from the analysis.

---

# 14. Project Learning Notes

This project was also used as a practical SQL learning exercise.

## SQL Basics

* `SELECT`
* `WHERE`
* `GROUP BY`
* `ORDER BY`
* `COUNT`
* `COUNTIF`
* `COUNT(DISTINCT ...)`
* `SUM`
* `ROUND`
* `MIN`
* `MAX`

## Data Transformation

* `PARSE_DATE`
* `UNNEST`
* `TIMESTAMP_MICROS`
* `TIMESTAMP_DIFF`
* `CONCAT`
* `CAST`

## Advanced SQL Concepts

* Common Table Expressions (`WITH`)
* Window functions
* `LAG()`
* `CASE`
* Deduplication logic
* Multi-table joins
* Data reconciliation
* Correlation analysis

---

# 15. Important SQL Concepts Learned

## 15.1 Common Table Expression

A CTE means **Common Table Expression**.

It is created using:

```sql
WITH
```

A CTE allows a complex query to be divided into smaller logical steps.

For example:

```sql
WITH purchase_events AS (
  ...
),

classified_purchases AS (
  ...
),

valid_purchases AS (
  ...
)

SELECT
  ...
```

### Simple Explanation

Instead of writing one huge query, I can create temporary logical steps and use the result of one step in the next step.

### Français

Un CTE permet de diviser une requête SQL complexe en plusieurs étapes logiques plus faciles à comprendre.

---

## 15.2 Window Function

A window function performs calculations across related rows without collapsing them into a single row.

Example:

```sql
LAG(event_timestamp) OVER (
  PARTITION BY transaction_id
  ORDER BY event_timestamp
)
```

`LAG()` allows the query to access a previous row.

In this project, it was used to compare purchase events and identify suspicious repeated purchase records.

---

## 15.3 UNNEST

`UNNEST()` is used when working with nested arrays.

In this project:

```sql
UNNEST(items)
```

turns the products contained inside the `items` array into individual rows.

This made it possible to analyze:

* products
* prices
* quantities
* brands
* categories
* product interactions

---

## 15.4 JOIN

A `JOIN` combines information from different tables.

For example:

```text
orders
   +
order_items
```

can be connected using:

```text
order_id
```

This allows order-level information to be connected with product-level information.

---

# 16. Data Quality Decisions

The following decisions were made during the project.

### User IDs

Rows without `user_pseudo_id` were excluded from `cleaned_events` because user-level analysis is central to the project.

### Invalid Product Names

Products with:

```text
(not set)
```

were excluded from product analysis.

### Missing Transaction IDs

Rows without transaction IDs were retained in the cleaned event-item staging table because they could still be useful for product and event analysis.

They were excluded from the valid order model because transaction IDs are required to establish order-level records.

### Invalid Transaction IDs

The value:

```text
(not set)
```

was treated as an invalid transaction ID rather than a real transaction identifier.

### Duplicate Purchases

A 10-second operational deduplication rule was applied to suspicious repeated purchase events.

This was an analytical rule designed to reduce likely duplicate event records. It should not be interpreted as a universally proven definition of a duplicate purchase.

### Revenue

GA4 purchase revenue is preserved as the official order-level revenue metric.

Product-level revenue is calculated independently using:

```text
price × quantity
```

The small reconciliation difference was documented rather than artificially corrected.

---

# 17. Current Project Structure

```text
E-Commerce-Revenue-Recovery/

│
├── 01_exploration.sql
│
├── 02_cleaning.sql
│
├── 03_data_model.sql
│
├── 04_business_analysis.sql
│
├── PROJECT_DOCUMENTATION.md
│
└── README.md
```

### File Responsibilities

**01_exploration.sql**

Explores the raw dataset and identifies data-quality and structural issues.

**02_cleaning.sql**

Cleans and prepares event-level and product-level data.

**03_data_model.sql**

Creates the analytical tables:

* customers
* products
* orders
* order_items

**04_business_analysis.sql**

Answers business questions using the analytical model and supporting raw GA4 fields where necessary.

**PROJECT_DOCUMENTATION.md**

Contains the detailed methodology, SQL logic, results, explanations, data-quality decisions, limitations, and interview notes.

**README.md**

Provides a shorter portfolio-friendly overview of the project.

---

# 18. Project Summary

This project transforms raw GA4 e-commerce event data into a structured analytical model and uses SQL to investigate customer behavior, product performance, conversion, and potential revenue recovery opportunities.

The main workflow is:

```text
RAW GA4 DATA
      ↓
DATA EXPLORATION
      ↓
DATA CLEANING
      ↓
DATA QUALITY CHECKS
      ↓
DATA MODELING
      ↓
CUSTOMERS / PRODUCTS / ORDERS / ORDER_ITEMS
      ↓
BUSINESS ANALYSIS
      ↓
INSIGHTS
      ↓
REVENUE RECOVERY OPPORTUNITIES
```

The project demonstrates practical skills in:

* SQL
* Google BigQuery
* Data cleaning
* Data validation
* Data modeling
* Nested data handling
* CTEs
* Window functions
* Deduplication
* Joins
* Revenue reconciliation
* Funnel analysis
* Product analysis
* Customer analysis
* Business problem solving

---

# 19. Interview Explanation

### "Tell me about your project."

> "I built an e-commerce analytics project using Google's GA4 sample e-commerce dataset in BigQuery. I started by exploring the raw event data and identifying data-quality issues such as missing transaction IDs, nested product information, and repeated purchase events. I then cleaned the data and created an analytical model with customers, products, orders, and order_items tables. I used SQL window functions and a defined operational rule to investigate suspicious duplicate purchases. Finally, I analyzed the customer funnel, product engagement, customer purchasing behavior, and traffic sources to identify where users were dropping out of the purchasing journey and where potential revenue recovery opportunities could be investigated."

---

# 20. Current Key Findings

## Customer Funnel

* **61,252** users recorded a product view.
* **12,545** users recorded an add-to-cart event.
* **9,715** users recorded a checkout event.
* **5,751** users recorded an add-payment-info event.
* **4,419** users recorded a purchase event.

## Conversion

Item-view-to-purchase user-level event conversion:

**7.21%**

## Largest Funnel Drop

The largest numerical drop occurred between:

```text
View Item → Add to Cart
```

Conversion:

**20.48%**

Users not progressing to the next stage:

**48,707**

## Second Major Drop

The second major numerical drop occurred between:

```text
Add Shipping Info → Add Payment Info
```

Conversion:

**59.20%**

Users not progressing to the next stage:

**3,963**

## Product Performance

The Google Tracking Hat recorded:

* **1,414 unique viewers**
* **0 recorded add-to-cart users**
* **0.00% view-to-cart rate**

Among products with at least 1,000 viewers, this was the lowest observed rate.

## Customer Behavior

* **3,713** purchasing customers
* **468** repeat customers
* **12.60%** repeat purchase rate
* **9,630** cart users without a recorded purchase
* **5,296** checkout users without a recorded purchase

## Revenue

Analytical order revenue:

**$311,376**

Calculated product-level revenue:

**$311,503**

Difference:

**$127**

Difference percentage:

**0.11%**

---

# 21. Conclusion

The project established a structured analytical foundation for investigating e-commerce customer behavior and potential revenue recovery opportunities.

The funnel analysis identified the largest numerical loss between product viewing and add-to-cart activity, followed by a significant drop between shipping information and payment information.

Product analysis also identified substantial differences in view-to-cart behavior across products. The Google Tracking Hat was particularly notable because it recorded product views but no recorded add-to-cart activity.

Customer analysis showed that most purchasing customers were one-time customers, while repeat customers generated higher cumulative revenue per customer because they placed multiple orders.

The analysis also examined device behavior and traffic sources. These analyses provide additional context but do not establish causation or channel profitability.

Overall, the project demonstrates how raw event data can be transformed into a structured analytical model and then used to identify measurable business patterns.

The next step is to translate these findings into practical, evidence-based business recommendations while clearly separating observed data patterns from assumptions about their causes.

---

