
/*******************************************************************************
  Project: E-Commerce Revenue Recovery & Conversion Optimization
  File: 03_data_model.sql
  Dialect: Google BigQuery Standard SQL
  Author: Mylene Gadeau

  Description:
  This script organizes the cleaned e-commerce data into separate tables
  that are easier to analyze. It creates customer and product tables,
  along with order and order item tables. The goal is to make the data
  more structured and easier to use for business analysis.
*******************************************************************************/


-- =============================================================================
-- SECTION 1: CUSTOMER TABLE
-- =============================================================================

-- Create one record per customer.
-- This table keeps basic information about when the customer was first
-- and last seen, their country, and the device they mainly use.

CREATE OR REPLACE TABLE `e-commerce-revenue-recovery.ecommerce_analytics.customers` AS
SELECT
  user_pseudo_id AS customer_id,

  -- First date the customer appeared in the dataset
  MIN(DATE(TIMESTAMP_MICROS(event_timestamp))) AS first_seen_date,

  -- Most recent date the customer appeared in the dataset
  MAX(DATE(TIMESTAMP_MICROS(event_timestamp))) AS last_seen_date,

  -- Customer's country
  MAX(country) AS country,

  -- Device category associated with the customer
  MAX(device_category) AS primary_device

FROM
  `e-commerce-revenue-recovery.ecommerce_analytics.cleaned_events`

WHERE
  user_pseudo_id IS NOT NULL

GROUP BY
  customer_id;


-- =============================================================================
-- SECTION 2: PRODUCT TABLE
-- =============================================================================

-- Create one record for each product.
-- This table contains the product name and an estimated unit price.

CREATE OR REPLACE `e-commerce-revenue-recovery.ecommerce_analytics.products` AS
SELECT DISTINCT
  product_id,
  product_name,

  -- Estimate the price of one unit using item revenue divided by quantity.
  -- MAX is used to keep one price value per product.
  ROUND(MAX(SAFE_DIVIDE(item_revenue, quantity)), 2) AS estimated_unit_price

FROM
  `e-commerce-revenue-recovery.ecommerce_analytics.cleaned_product_events`

WHERE
  product_id IS NOT NULL

GROUP BY
  product_id,
  product_name;


-- =============================================================================
-- SECTION 3: ORDERS TABLE
-- =============================================================================

-- Create one record per completed order.
-- This table connects each order to a customer and records the
-- order date and total revenue.

CREATE OR REPLACE TABLE `e-commerce-revenue-recovery.ecommerce_analytics.orders` AS
SELECT
  transaction_id AS order_id,
  user_pseudo_id AS customer_id,
  DATE(TIMESTAMP_MICROS(event_timestamp)) AS order_date,

  -- Total revenue generated by the order
  ROUND(SUM(purchase_revenue), 2) AS revenue

FROM
  `e-commerce-revenue-recovery.ecommerce_analytics.cleaned_events`

WHERE
  event_name = 'purchase'
  AND transaction_id IS NOT NULL

GROUP BY
  order_id,
  customer_id,
  order_date;


-- =============================================================================
-- SECTION 4: ORDER ITEMS TABLE
-- =============================================================================

-- Create one record for each product included in an order.
-- This allows us to analyze which products were purchased,
-- how many units were sold, and how much revenue they generated.

CREATE OR REPLACE TABLE `e-commerce-revenue-recovery.ecommerce_analytics.order_items` AS
SELECT
  transaction_id AS order_id,
  product_id,
  product_name,

  -- Total number of units of the product in the order
  SUM(quantity) AS quantity,

  -- Total revenue generated by the product in the order
  ROUND(SUM(item_revenue), 2) AS item_revenue

FROM
  `e-commerce-revenue-recovery.ecommerce_analytics.cleaned_product_events`

WHERE
  transaction_id IS NOT NULL
  AND product_id IS NOT NULL

GROUP BY
  order_id,
  product_id,
  product_name;
```
